[tool.poetry]
name = "brick-tq-shacl"
version = "0.3.4a1"
description = "Wraps topquadrant's SHACL implementation in a simple Python wrapper"
authors = ["Gabe Fierro <gtfierro@mines.edu>"]
include = ["brick_tq_shacl/topquadrant_shacl"]
license = "bsd-3-clause"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8.1,<4.0"
rdflib = "^7.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
